# Generated by Django 6.0 on 2025-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
