# Generated by Django 6.0 on 2025-12-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_name_student_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='name',
        ),
    ]
