# Generated by Django 6.0 on 2025-12-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_student_id_student_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
    ]
