# Generated by Django 6.0 on 2025-12-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_semester_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
    ]
