# Generated by Django 6.0 on 2025-12-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_attendancerecord_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
